package com.happy.video.entity;

import java.util.Date;

/**
 * tools_item
 * 
 * @author bianj
 * @version 1.0.0 2020-09-17
 */
public class ToolsItem implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -9093334313379201876L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** name */
    private String name;

    /** toolsUrl */
    private String toolsUrl;

    /** imgUrl */
    private String imgUrl;

    /** toolsTypeId */
    private Integer toolsTypeId;

    /** flag */
    private Integer flag;

    /** createTime */
    private Date createTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取name
     * 
     * @return name
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置name
     * 
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * 获取toolsUrl
     * 
     * @return toolsUrl
     */
    public String getToolsUrl() {
        return this.toolsUrl;
    }

    /**
     * 设置toolsUrl
     * 
     * @param toolsUrl
     */
    public void setToolsUrl(String toolsUrl) {
        this.toolsUrl = toolsUrl;
    }

    /**
     * 获取imgUrl
     * 
     * @return imgUrl
     */
    public String getImgUrl() {
        return this.imgUrl;
    }

    /**
     * 设置imgUrl
     * 
     * @param imgUrl
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    /**
     * 获取toolsTypeId
     * 
     * @return toolsTypeId
     */
    public Integer getToolsTypeId() {
        return this.toolsTypeId;
    }

    /**
     * 设置toolsTypeId
     * 
     * @param toolsTypeId
     */
    public void setToolsTypeId(Integer toolsTypeId) {
        this.toolsTypeId = toolsTypeId;
    }

    /**
     * 获取flag
     * 
     * @return flag
     */
    public Integer getFlag() {
        return this.flag;
    }

    /**
     * 设置flag
     * 
     * @param flag
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * 获取createTime
     * 
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     * 
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */

    @Override
    public String toString() {
        return "ToolsItem{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", toolsUrl='" + toolsUrl + '\'' +
                ", imgUrl='" + imgUrl + '\'' +
                ", toolsTypeId=" + toolsTypeId +
                ", flag=" + flag +
                ", createTime=" + createTime +
                '}';
    }
}